backend:
  name: github
  repo: bert-bruggeman/balonissimo.new
  branch: master

media_folder: "/media/"

collections:
  - name: "page"
    label: "Pages"
    folder: "_pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2"}
      - {label: "Permalink", name: "permalink", widget: "string" }
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Layout", name: "layout", widget: "select", required: false, options: ["page", "frontpage", "flights", "testimonials", "media"], default: "page" }
      - {label: "Language", name: "lang", widget: "select", required: false, options: ["en", "pt", "nl"], default: "en" }
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "galleries"
    label: "Galleries"
    folder: "_galleries"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2"}
      - {label: "Permalink", name: "permalink", widget: "string" }
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Language", name: "lang", widget: "select", required: false, options: ["en", "pt", "nl"], default: "en" }
      - {label: "Description", name: "description", widget: "text"}
      - {label: "instagram tag", name: "instagram", widget: "string", required: true }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "flights"
    label: "Flights"
    folder: "_flights"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2"}
      - {label: "Permalink", name: "permalink", widget: "string" }
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Language", name: "lang", widget: "select", required: false, options: ["en", "pt", "nl"], default: "en" }
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string" }
      - {label: "Image", name: "image", widget: "image", required: false }
      - {label: "instagram tag", name: "instagram", widget: "string", required: true }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "teasers"
    label: "Teasers frontpage"
    folder: "_teasers"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Language", name: "lang", widget: "select", required: false, options: ["en", "pt", "nl"], default: "en" }
      - {label: "Image", name: "image", widget: "image", required: false }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "testimonials"
    label: "Testimonials"
    folder: "_testimonials"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Language", name: "lang", widget: "select", required: false, options: ["en", "pt", "nl"], default: "en" }
      - {label: "Name", name: "name", widget: "string" }
      - {label: "Date", name: "date", widget: "date" }
      - {label: "Flight", name: "Flight", widget: "string" }
      - {label: "Image", name: "image", widget: "image", required: false }
      - {label: "instagram tag", name: "instagram", widget: "string", required: true }
      - {label: "Body", name: "body", widget: "markdown"}
