backend:
  name: github
  repo: Balonissimo/balonissimo.com
  branch: master

media_folder: "/media/"

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2"}
      - {label: "Permalink", name: "permalink", widget: "string" }
      - {label: "Layout", name: "layout", widget: "select", required: false, options: ["page", "frontpage", "flights", "testimonials", "media"], default: "page" }
      - {label: "Language", name: "lang", widget: "select", required: false, options: ["en", "pt", "nl"], default: "en" }
      - {label: "Image", name: "image", widget: "image", required: false }
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Buttons"
        name: buttons
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Link", name: "url", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
