backend:
  name: github
  repo: bert-bruggeman/balonissimo.new
  branch: master

media_folder: "/media/"

collections:
  - name: "page"
    label: "Page"
    folder: "_pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2"}
      - {label: "Permalink", name: "permalink", widget: "string" }
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Layout", name: "layout", widget: "select", required: false, options: ["page", "frontpage", "flights", "testimonials", "media"], default: "page", tagname: "" }
      - {label: "Language", name: "lang", widget: "select", required: false, options: ["en", "pt", "nl"], default: "en", tagname: "" }
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "galleries"
    label: "Galleries"
    folder: "_galleries"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2"}
      - {label: "Permalink", name: "permalink", widget: "string" }
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Language", name: "lang", widget: "select", required: false, options: ["en", "pt", "nl"], default: "en" }
      - {label: "Description", name: "description", widget: "text"}
      - {label: "instagram tag", name: "instagram", widget: "string", required: true }
      - {label: "Body", name: "body", widget: "markdown"}
